#!/bin/sh
export LANG="ru_RU.utf8"

userresources=$HOME/.Xdefaults
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

setxkbmap -layout us,ru -variant dvp,typewriter -option grp:shift_toggle,grp:caps_toggle,grp_led:caps,compose:rctrl,grp:lwin

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

xset +fp /usr/share/fonts/local &
xset fp rehash &
xrdb -merge ~/.Xdefaults &

xcape &

xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200

urxvtd -q -f -o &

#feh --bg-scale ~/media/pics/wallpaper &
#xcompmgr &
#   xautolock -locker lock.sh -detectsleep -secure &
#~/work/repos/dzen2-notify/dzen2_notify_daemon.py &
#   pulsar &

exec /usr/bin/ssh-agent i3
