# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# if [[ -n $SSH_CONNECTION ]]; then
    # tmux at default
# fi


# Tab-completion

PATH=$PATH:~/bin:~/.gem/ruby/2.1.0/bin

autoload -U compinit
compinit
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
setopt completealiases
zstyle ':completion:*' menu select
# zstyle ':completion::complete:*' use-cache 1

# Simple gentoo prompt
autoload -U promptinit
promptinit; prompt adam2

# http://stackoverflow.com/questions/1128496/to-get-a-prompt-which-indicates-git-branch-in-zsh
setopt prompt_subst
autoload -Uz vcs_info
zstyle ':vcs_info:*' actionformats \
    '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
zstyle ':vcs_info:*' formats       \
    '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{5}]%f '
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{3}%r'
zstyle ':vcs_info:*' enable git cvs svn

vcs_info_wrapper() {
  vcs_info
  if [ -n "$vcs_info_msg_0_" ]; then
    echo "%{$fg[grey]%}${vcs_info_msg_0_}%{$reset_color%}$del"
  fi
}

RPROMPT=$'$(vcs_info_wrapper)'

bindkey -e

autoload edit-command-line
zle -N edit-command-line
bindkey '^v' edit-command-line

export HISTSIZE=2000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_ignore_space


setopt autocd
# setopt extendedglob # Extended regular expressions cp ^*.(tar.

alias -g L='| less'
alias -g H='| head'
alias -g T='| tail -n 1000'
alias -g G='| grep'
alias -g S='| sed'
alias -g ts='date +%s'

alias glg='git log --oneline --graph'
alias gpl='git pull --rebase'
alias gm='git merge --no-ff'
alias gis='git status -s'
alias ga='git add'
alias gc='git commit'

alias tm='tmux attach || tmux new'
alias mvim='open -a MacVim'
alias vim='nvim -u ~/.myvimrc'
alias vc='nvim -u ~/.myvimrc -O ~/.myvimrc ~/.vimrc'
alias is='cd ~/work/InnoShop/ && va && cd innoshop'


# export EDITOR=vim

function va() {
    source ~/.virtualenvs/$(basename `pwd`)/bin/activate
}
