image: guix
packages:
  - make
sources:
  - https://git.sr.ht/~abcdw/rde
tasks:
  - check: |
      cd rde
      make check
  # # It takes too much time rn.
  # - build-example-home: |
  #     cd rde
  #     make examples/ixy/home/build
