image: guix
packages:
  - make
sources:
  - https://git.sr.ht/~abcdw/rde
tasks:
  - check: |
      cd rde
      make check
  - build-minimal-example-home: |
      cd rde/examples
      make minimal/home/build
triggers:
  - action: email
    condition: failure
    to: ~abcdw/rde-devel@lists.sr.ht
