(define-module (rde emacs packages)
  #:use-module (guix build-system emacs)
  #:use-module (guix store)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix packages)
  #:use-module (gnu packages autotools)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages webkit)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages emacs)
  #:use-module (gnu packages emacs-xyz)
  #:use-module (gnu packages sqlite)
  #:use-module (guix build emacs-utils)
  #:use-module (ice-9 pretty-print)
  #:use-module (guix utils)
  #:use-module (srfi srfi-1)
  #:use-module ((guix licenses) #:prefix license:)
  #:export (%rde-emacs-all-packages))

(define-public emacs-rde-core
  (package
    (name "emacs-rde-core")
    (version "0.2.0")
    (build-system emacs-build-system)
    (source (local-file "rde-core.el"))
    (propagated-inputs `(("use-package" ,emacs-use-package)
			 ("delight" ,emacs-delight)))
    (synopsis "use-package initialization for rde-emacs")
    (description "Compile time dependency for rde emacs packags.")
    (home-page "https://github.com/abcdw/rde")
    (license license:gpl3+)))

(define-public emacs-rde-use-package
  (package
    (name "emacs-rde-use-package")
    (version "0.2.0")
    (build-system emacs-build-system)
    (source (local-file "rde-use-package.el"))
    (propagated-inputs `(("use-package" ,emacs-use-package)))
    (synopsis "use-package initialization for rde-emacs")
    (description "Compile time dependency for rde emacs packags.")
    (home-page "https://github.com/abcdw/rde")
    (license license:gpl3+)))

(define-public emacs-rde-variables
  (package
    (name "emacs-rde-variables")
    (version "0.2.0")
    (build-system emacs-build-system)
    (source (local-file "rde-variables.el"))
    ;; (inputs `(("emacs-rde-core" ,emacs-rde-core)))
    (synopsis "Set of variables for emacs, generated by rde")
    (description "Varibles that can be used by rde emacs packages.")
    (home-page "https://github.com/abcdw/rde")
    (license license:gpl3+)))

(define-public emacs-rde-faces
  (package
    (name "emacs-rde-faces")
    (version "0.2.0")
    (build-system emacs-build-system)
    (source (local-file "rde-faces.el"))
    (inputs `(("emacs-rde-use-package" ,emacs-rde-use-package)))
    (synopsis "Set default fonts and other faces")
    (description "")
    (home-page "https://github.com/abcdw/rde")
    (license license:gpl3+)))

(define-public emacs-rde-early-init
  (package
    (name "emacs-rde-early-init")
    (version "0.2.0")
    (build-system emacs-build-system)
    (source (local-file "early-init.el"))
    (synopsis "Different tweaks for faster startup")
    (description "In addition to tweaks, disables GUI elements")
    (home-page "https://github.com/abcdw/rde")
    (license license:gpl3+)))

(define-public emacs-rde-org-roam
  (package
    (name "emacs-rde-org-roam")
    (version "0.2.0")
    (build-system emacs-build-system)
    (source (local-file "rde-org-roam.el"))
    (inputs `(("emacs-rde-use-package" ,emacs-rde-use-package)))
    (propagated-inputs `(("emacs-org-roam" ,emacs-org-roam)
			 ("sqlite3" ,sqlite)))
    (synopsis "Enables org-roam and configures basic hotkeys")
    (description "")
    (home-page "https://github.com/abcdw/rde")
    (license license:gpl3+)))

(define-public emacs-rde-modus-themes
  (package
    (name "emacs-rde-modus-themes")
    (version "0.2.0")
    (build-system emacs-build-system)
    (source (local-file "rde-modus-themes.el"))
    (inputs `(("emacs-rde-use-package" ,emacs-rde-use-package)))
    (propagated-inputs `(("emacs-modus-themes" ,emacs-modus-themes)))
    (synopsis "Few tweaks for modus themes")
    (description "")
    (home-page "https://github.com/abcdw/rde")
    (license license:gpl3+)))

(define-public emacs-rde-default-init
  (package
    (name "emacs-rde-default-init")
    (version "0.2.0")
    (build-system emacs-build-system)
    (propagated-inputs `(("emacs-rde-core" ,emacs-rde-core)
			 ("emacs-rde-variables" ,emacs-rde-variables)
			 ("emacs-rde-faces" ,emacs-rde-faces)
			 ("emacs-rde-org-roam" ,emacs-rde-org-roam)
			 ("emacs-rde-modus-themes" ,emacs-rde-modus-themes)
			 ("emacs-orderless" ,emacs-orderless)))
    (source (local-file "default.el"))
    (synopsis "Init file")
    (description "")
    (home-page "https://github.com/abcdw/rde")
    (license license:gpl3+)))

;; (define emacs-rde-init
;;   (text-file
;;    "init.el"
;;    (fold (lambda (package)
;; 	   (string-append "(require '"
;; 			  (string-drop (package-name package) 6)
;; 			  ")")))))

;; (define-public emacs-rde-init
;;   (package
;;     (name "emacs-rde-early-init")
;;     (version "0.2.0")
;;     (build-system emacs-build-system)
;;     (source init-el
;;      )
;;     (synopsis "Requires all rde-* packages")
;;     (description "Requires all rde-* packages")
;;     (home-page "https://github.com/abcdw/rde")
;;     (license license:gpl3+)))

;; (symlink "./emacs-rde.el" "/home/abcdw/tmp-file.el")

;; (define rde-emacs-packages
;;   '(emacs-use-package))

(define-public emacs-next-pgtk-latest
  (let ((commit "565d8f57d349c19d9bbb5d5d5fdacf3c70b85d42")
        (revision "0"))
    (package/inherit emacs-next
      (name "emacs-next-pgtk-latest")
      (version (git-version "28.0.50" revision commit))
      (source
       (origin
         (method git-fetch)
         (uri (git-reference
               (url "https://git.savannah.gnu.org/git/emacs.git/")
               (commit commit)))
         (file-name (git-file-name name version))
         (sha256
          (base32
           "0y23gn2ppphx1g1x0b7gvqh3x36byphfzllsl74giybd5j6sfyx3"))))
      (arguments
       (substitute-keyword-arguments (package-arguments emacs-next)
         ((#:configure-flags flags ''())
          `(cons* "--with-pgtk" "--with-xwidgets" ,flags))))
      (propagated-inputs
       `(("gsettings-desktop-schemas" ,gsettings-desktop-schemas)
         ("glib-networking" ,glib-networking)))
      (inputs
       `(("webkitgtk" ,webkitgtk)
         ,@(package-inputs emacs-next)))
      (home-page "https://github.com/masm11/emacs")
      (synopsis "Emacs text editor with @code{pgtk} and @code{xwidgets} support")
      (description "This is an unofficial Emacs fork build with a pure-GTK
graphical toolkit to work natively on Wayland.  In addition to that, xwidgets
also enabled and works without glitches even on X server."))))

(define %rde-emacs emacs-next-pgtk-latest)

(define %rde-emacs-runtime-packages
  (list
   ;; emacs-use-package
   ;; emacs-orderless
   ;; emacs-rde-core
   ;; emacs-rde-variables
   ;; emacs-rde-faces
   ;; emacs-rde-org-roam
   ;; emacs-rde-modus-themes
   emacs-rde-default-init))

(define %rde-emacs-all-packages
  (append
   (list %rde-emacs
	 emacs-guix
	 emacs-delight
	 emacs-telega
	 emacs-magit
	 emacs-pdf-tools
	 emacs-yasnippet
	 ;; emacs-rde-early-init
	 ;; emacs-rde-init
	 )
   %rde-emacs-runtime-packages))

;; (pretty-print "test")
;; (specifications->manifest
;;  '("emacs"))
