image: guix
packages:
  - make
sources:
  - https://git.sr.ht/~abcdw/rde
tasks:
  - build-minimal-example-home-latest-guix: |
      cd rde
      git switch keyring
      git switch --detach -
      cd examples

      if [[ "$BUILD_REASON" == "patchset" ]]; then
        make minimal/home/build/ci-latest-guix-no-auth
      else
        make minimal/home/build/ci-latest-guix
      fi
oauth: git.sr.ht/REPOSITORIES:RW git.sr.ht/PROFILE:RO
triggers:
  - action: email
    condition: failure
    to: ~abcdw/rde-devel@lists.sr.ht
