#!/bin/sh
feh --bg-scale ~/Pictures/bg.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          25
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a Chromium-browser desktop='^3'
bspc rule -a Brave-browser desktop='^5'
# bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

bspc config external_rules_command "${HOME}/.config/bspwm/external_rules"

bspc rule -a Alacritty:scratchterm rectangle=0x0+25+25 state=floating sticky=on

dunst &
gromit-mpx &
# "$(which external_rules)"

# chromium &
# telegram-desktop &
# emacs &

# xterm &
