#!/bin/sh

wid=$1
class=$2
instance=$3

# notify-send "$wid| $class| $instance| $(xtitle $wid)|"

if [ "$class" = TelegramDesktop ] ; then
   title=$(xtitle "$wid")
	    case "$title" in
		"Telegram")
			echo "desktop=^6 rectangle=1400x1370+1140+50 follow=on state=floating"
		;;
	esac
fi
title=$(xtitle "$wid")
  case "$title" in
		"meet.jit.si is sharing your screen.")
			echo "state=tiled sticky=off hidden=on"
		;;
esac
