#!/usr/bin/env sh
client_id=$1
client_privkey=`cat $2`
server_pubkey=`cat $3`
endpoint=$4

cat <<END
[Interface]
PrivateKey = $client_privkey
Address = 10.100.0.10$client_id/32
DNS = 8.8.8.8,208.67.222.222

[Peer]
PublicKey = $server_pubkey
Endpoint = $endpoint
AllowedIPs = 0.0.0.0/0
END
